config/routes.rb
Rails.application.routes.draw do
  root 'contacts#index'

  resources :users, only: [:create]
  get 'login', to: 'sessions#index'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#logout'
  get 'signup', to: 'sessions#new'

  resources :contacts, only: [:index, :show]

  namespace :api do
    namespace :v1 do
      post 'events', to: 'events#create'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  has_many :events, dependent: :destroy

  validates :email, presence: { message: 'Email field cannot be blank' }
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :contact

  event_types = ['processed', 'dropped', 'delivered', 'deferred', 'bounce', 'blocked', 'open', 'click', 'spamreport', 'unsubscribe', 'group_unsubscribe', 'group_resubscribe']
  enum event_type: event_types.zip(event_types).to_h # Every enum value represented as a string of itself

  validates :contact, presence: true
  validates :event_type, inclusion: { in: event_types, message: 'Invalid event type' }
  validates :timestamp, numericality: { only_integer: true, message: 'timestamp must be in Unix format' }
  validates :sg_event_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/api/v1/events_controller.rb
class Api::V1::EventsController < ApplicationController
  skip_before_action :authorise_user

  # The authenticity token is used to prevent CSRF attacks.
  # Seeing as this is a general API endpoint, we don't need this protection. 
  skip_before_action :verify_authenticity_token

  # POST /api/v1/events
  def create
    contact = Contact.find_or_create_by(email: events_params[:email])

    if contact.errors.present?
      return render json: { error: contact.errors.map(&:message) }, status: 422
    end

    event = contact.events.find_or_create_by(sg_event_id: events_params[:sg_event_id])

    begin
      event.update(events_params.except(:email))
    rescue ArgumentError => error
      # event_type enum can only throw ArgumentError instead of going through the validator
      return render json: { error: error.message }, status: 422
    rescue ActiveRecord::RecordNotUnique
      return render json: { error: 'An event with this sg_event_id already exists under a different email' }, status: 422
    end

    if event.errors.present?
      return render json: { error: event.errors.map(&:message) }, status: 422
    end

    render json: {}, status: 200
  end

  private

  def events_params
    sanitised_params = params.permit(
      :email,
      :timestamp,
      :sg_event_id,
      :event,
      :type
    )

    # Rename :event param to :event_type
    # Event types 'bounce' and 'blocked' come in as two separate parameters.
    # When it's bounce, :event is 'bounce' and :type is 'bounce'.
    # When it's blocked, :event is 'bounce' and :event is 'blocked'.
    sanitised_params[:event_type] = (sanitised_params[:event] == 'bounce') ? sanitised_params[:type] : sanitised_params[:event]

    sanitised_params.delete(:event)
    sanitised_params.delete(:type)

    pp params[0]
    pp sanitised_params
    return sanitised_params
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  helper_method :logged_in?

  before_action :authorise_user

  def current_user
    User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end

  def authorise_user
    redirect_to login_path unless logged_in?
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
    @contacts = Contact.all
  end

  def show
    @contact = Contact.find(params[:id])
    @events = @contact.events.order('timestamp DESC')
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorise_user

  def index
    redirect_to contacts_path if logged_in?
  end

  def new
    @user = User.new
  end

  def create
    @user = User.find_by(username: params[:username])

    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      return redirect_to contacts_path
    end

    redirect_to login_path, alert: 'Username or password is incorrect.'
  end

  def logout
    session[:user_id] = nil
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorise_user

  def create
    @user = User.create(params.require(:user).permit(:username, :password))
    session[:user_id] = @user.id

    redirect_to login_path
  end
end

app/helpers/api/v1/events_helper.rb
module Api::V1::EventsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contacts/index.html.erb
<div class="contacts">
  <h2 class="contacts__title">Contacts</h2>

  <div class="contacts__list">
    <% if @contacts.present? %>
      <% @contacts.each do |contact| %>
        <a class="contacts__contact" href="<%= contact_path(contact.id) %>">
          <h3 class="contacts__email"><%= contact.email %></h3>

          <span class="contacts__event_count"><%= pluralize(contact.events.count, 'event') %></span>
        </a>
      <% end %>
    <% else %>
      <div class="contacts__empty">
        <p>No contacts yet.</p>
      </div>
    <% end %>
  </div>
</div>

app/views/contacts/show.html.erb
<div class="contact">
  <%= button_to 'Back to contacts', contacts_path, method: :get %>

  <h2>Events for <%= @contact.email %></h2>

  <div class="contact__events">
    <% @events.each do |event| %>
      <%# TODO: pretty timestamp should be in a model method %>
      <% timestamp = Time.at(event.timestamp).to_datetime %>
      <div class="contact__event">
        <div class="contact__header">
          <h3 class="contact__title"><%= event.event_type.capitalize %></h3> 
          &middot;
          <span><%= timestamp.strftime('%H:%M:%S') %> on <%= timestamp.strftime('%B %e, %Y') %></span>
        </div>

        <p class="contact__sg-event-id">Sendgrid event ID: <%= event.sg_event_id %></p>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Secretary</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="app">
      <div class="app__wrapper">
        <header class="app__heading">
          <% if logged_in? %>
            <%= button_to 'Log out', logout_path, method: :get, class: 'heading__logout' %>
          <% end %>

          <h1 class="heading__title">
            Secretary
          </h1>

          <% if logged_in? %>
            <p class="heading__subtitle">
              Here's what happened to your emails when you weren't looking...
            </p>
          <% end %>
        </header>

        <%= yield %>
      </div>
    </div>
  </body>
</html>